Issue 384 rebased
wfau/aglais pull request #480
Opened 2021-05-11 15:43 UTC by stvoutsin

Changes to enable Prometheus & Grafana monitoring for the Ansible based Hadoop/Spark deploy.
This PR replaces https://github.com/wfau/aglais/pull/457 and includes more recent changes to the wfau/master branch

2021-05-12 12:06 UTC, Zarquan requested changes
Prefix variables with the role name.
Use the latest version wherever possible. If the latest version doesn't work, then need to add a comment describing why.

2021-05-12 12:06 UTC, Zarquan commented on deployments/hadoop-yarn/ansible/roles/prometheus/vars/main.yml
> +version: "2.3.2"
Why are we installing an old version ?
https://github.com/prometheus/prometheus/releases
https://github.com/prometheus/prometheus/releases/latest
```suggestion
version: "2.26.0"
```

2021-05-12 12:06 UTC, Zarquan commented on deployments/hadoop-yarn/ansible/roles/prometheus_node_exporter/vars/main.yml
> +version: 0.16.0
Why are we installing an old version ?
https://github.com/prometheus/node_exporter/releases
https://github.com/prometheus/node_exporter/releases/latest
```suggestion
version: 1.1.2
```

2021-05-14 16:52 UTC, stvoutsin commented
I've accepted the suggestions, made some minor fixes (typos to var names), and run a test deploy successfully. I did not run any Spark jobs in the test deploy, just checked the Grafana Dashboard to see that the node metrics are getting harvested.

2021-05-17 18:57 UTC, Zarquan commented
> I did not run any Spark jobs in the test deploy, just checked the Grafana Dashboard to see that the node metrics are getting harvested.
It would be good to run at least one real world Spark example, the RandomForest is the one I've been using, just to check that (a) this doesn't break Spark for some unknown reason, and (b) we can get some useful metrics about a Spark run out of it.

I have no idea how this PR could break Spark or Zeppelin, but we should check it before we merge, just in case.

Until we have an automated testing in place I think we should consider a set of notes describing a manual run of the RandomForest notebook the minimal acceptance test for a merge.

2021-05-19 03:52 UTC, Zarquan approved these changes

2021-05-19 03:53 UTC, merged