Re-enabling gaiaxpy
wfau/aglais pull request #626
Opened 2022-01-31 12:57 UTC by stvoutsin

Change to re-enable gaiaxpy installation, and notes on tests with gaiaxpy enabled.

2022-01-31 13:14 UTC, Zarquan commented
If we have a plan or issue for an automated test already in progress elsewhere, then this is OK to merge.
If not then can we add an automated test here ?

2022-01-31 13:17 UTC, Zarquan requested changes
If we have a plan/issue for an automatic test in progress elsewhere then this is good to go.
If we don't have an automated test yet, then can we add one here ?

2022-01-31 13:23 UTC, Zarquan commented
If we already have an automated test for our Python libraries, then adding this one to the list should be enough.
If we have an active issue in progress to add an automated test for our Python libraries, then adding this one to the list should be enough.

2022-02-03 15:41 UTC, Zarquan reviewed
Is this a fair summary:

* Using dependency versions from GaiaXPy.
  210 passed, 3 warnings

* Using dependency versions from Aglais.
  1 failed, 209 passed, 121 warnings

* Using dependency versions from Aglais but  downgrading pandas to version from GaiaXPy.
  210 passed, 4160 warnings

Questions:
* What does this do to our own test notebooks ?
* How bad are the 4160 warnings ?

2022-02-04 13:09 UTC, stvoutsin commented on notes/stv/20220131-gaiaxpy-deploy-benchmark.txt
> +> Took 2 sec. Last updated by admin at January 31 2022, 12:35:15 PM.
I have a notebook that test the versions of the installed libraries, which we could include in the notebooks.json config file that is included in this repo. However we probably should first figure out which versions of the different packages will be installed, and whether we will included gaiaxpy or not due to the package compatibility issues.

2022-02-04 13:12 UTC, stvoutsin commented on notes/stv/20220131-gaiaxpy-deploy-benchmark.txt
> +> WARNING: IERSStaleWarning: leap-second file is expired. [astropy.utils.iers.iers]
I have only seen it when importing gaiaxpy, although the exception is triggered in an astropy module. Here's a github issue that seems related: https://github.com/astropy/astropy/issues/10228

2022-02-04 13:13 UTC, Zarquan commented on notes/stv/20220131-gaiaxpy-deploy-benchmark.txt
> +> WARNING: IERSStaleWarning: leap-second file is expired. [astropy.utils.iers.iers]
Is it a problem, or can we safely ignore it ?

2022-02-04 13:14 UTC, stvoutsin commented
> Is this a fair summary:
> 
> * Using dependency versions from GaiaXPy.
>   210 passed, 3 warnings
> * Using dependency versions from Aglais.
>   1 failed, 209 passed, 121 warnings
> * Using dependency versions from Aglais but  downgrading pandas to version from GaiaXPy.
>   210 passed, 4160 warnings
> 
> Questions:
> 
> * What does this do to our own test notebooks ?
> * How bad are the 4160 warnings ?

Yes that's correct. I can run a test with only pandas downgraded and see how our notebooks behave, but we'd still be downgrading a package which seems ugly

2022-02-04 13:14 UTC, Zarquan commented on notes/stv/20220131-gaiaxpy-deploy-benchmark.txt
> +> Took 2 sec. Last updated by admin at January 31 2022, 12:35:15 PM.
So the library version test could include gaiaxpy in the list of things it checks ?

2022-02-04 13:15 UTC, Zarquan commented on notes/stv/20220131-gaiaxpy-deploy-benchmark.txt
> +> Took 2 sec. Last updated by admin at January 31 2022, 12:35:15 PM.
If so, then we can do that in a new issue/pr thread.

2022-02-04 13:17 UTC, Zarquan commented
Yep, we need to test to see if the rest of our notebooks work with the downgraded pandas version. If they don't then that isn't really an option.

2022-02-04 18:14 UTC, stvoutsin commented on notes/stv/20220131-gaiaxpy-deploy-benchmark.txt
> +> WARNING: IERSStaleWarning: leap-second file is expired. [astropy.utils.iers.iers]
I've seen this again today when checking the output of some of our Public Examples notebooks (Mean Proper Motions), the error appeared in the following cell.
https://github.com/wfau/aglais-notebooks/blob/40f85ed8c7585f43b0431a1b1297bfb64df12961/AglaisPublicExamples/Mean%20proper%20motions%20over%20the%20sky_2GSNYBDWB.zpln#L78
So perhaps we need to look into it?

2022-02-11 11:31 UTC, Zarquan approved these changes

2022-02-11 11:32 UTC, merged